<?php

// Auto generated by wpfluent Installer.

return array(
    'name'         => 'WebmakerrPro Pro',
    'slug'         => 'fluent-cart-pro',
    'domain_path'  => '/language',
    'text_domain'  => 'fluent-cart-pro',
    'hook_prefix'  => 'fluent-cart-pro/',
    'rest_version' => 'v2',
    'env'            => 'production',
);
